### ISSUE TITLE
点击菜单会出现错误

### ISSUE THREAD

**Issue by flashtony2005** [X-neuron/antdFront#19]
Something went wrong.
Cannot read properties of null (reading 'name')
是react  的版本的问题吗

**Comment by flashtony2005** [comment]
react-dom.development.js:67 Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in a useEffect cleanup function.
    at BaseForm (http://localhost:8080/static/js/398.chunk.js:5575:24)
    at RequestForm (http://localhost:8080/static/js/398.chunk.js:5926:23)
    at ProForm
    at div
    at Login (http://localhost:8080/static/js/398.chunk.js:19514:5)
    at Outlet (http://localhost:8080/static/js/bundle.js:70138:10)
    at div
    at div
    at UserLayout (http://localhost:8080/static/js/174.chunk.js:2073:62)
printWarning @ react-dom.development.js:67
BasicLayout.jsx:85 selectkey: /
react-dom.development.js:67 Warning: Each child in a list should have a unique "key" prop. See https://reactjs.org/link/warning-keys for more information.
    at div
    at BasicLayout (http://localhost:8080/static/js/234.chunk.js:16033:92)
    at Outlet (http://localhost:8080/static/js/bundle.js:70138:10)
    at SecurityLayout (http://localhost:8080/static/js/210.chunk.js:37:5)
    at Outlet (http://localhost:8080/static/js/bundle.js:70138:10)
    at BlankLayout
    at FormProvider (http://localhost:8080/static/js/bundle.js:38313:31)
    at LocaleProvider (http://localhost:8080/static/js/bundle.js:5054:99)
    at ProviderChildren (http://localhost:8080/static/js/bundle.js:4468:24)
    at LocaleReceiver (http://localhost:8080/static/js/bundle.js:4942:99)
    at ConfigProvider (http://localhost:8080/static/js/bundle.js:4576:13)
    at I18nProvider (http://localhost:8080/static/js/bundle.js:2678:19)
    at Suspense
    at Locale (http://localhost:8080/static/js/bundle.js:9507:5)
    at App (http://localhost:8080/static/js/bundle.js:8812:62)
    at Router (http://localhost:8080/static/js/bundle.js:70161:15)
    at BrowserRouter (http://localhost:8080/static/js/bundle.js:69699:5)
    at RecoilRoot_INTERNAL (http://localhost:8080/static/js/bundle.js:78432:3)
    at RecoilRoot (http://localhost:8080/static/js/bundle.js:78588:5)
printWarning @ react-dom.development.js:67
core.development.js:112 Plurals for locale zh-CN aren't loaded. Use i18n.loadLocaleData method to load plurals for specific locale. Using other plural rule as a fallback.
defaultFormats @ core.development.js:112
BasicLayout.jsx:85 selectkey: /
BasicLayout.jsx:100 Object
BasicLayout.jsx:85 selectkey: null
react-dom.development.js:20085 The above error occurred in the <TabRoute> component:

    at TabRoute (http://localhost:8080/static/js/234.chunk.js:15800:5)
    at main
    at Basic (http://localhost:8080/static/js/174.chunk.js:904:25)
    at Adapter (http://localhost:8080/static/js/174.chunk.js:887:66)
    at ErrorBoundary (http://localhost:8080/static/js/234.chunk.js:7128:5)
    at ConfigProviderWrap (http://localhost:8080/static/js/398.chunk.js:7680:23)
    at WrapContent (http://localhost:8080/static/js/234.chunk.js:1805:21)
    at div
    at section
    at BasicLayout (http://localhost:8080/static/js/174.chunk.js:919:63)
    at Adapter (http://localhost:8080/static/js/174.chunk.js:887:66)
    at div
    at Provider (http://localhost:8080/static/js/234.chunk.js:39740:31)
    at BasicLayout (http://localhost:8080/static/js/234.chunk.js:1200:66)
    at div
    at BasicLayout (http://localhost:8080/static/js/234.chunk.js:16033:92)
    at Outlet (http://localhost:8080/static/js/bundle.js:70138:10)
    at SecurityLayout (http://localhost:8080/static/js/210.chunk.js:37:5)
    at Outlet (http://localhost:8080/static/js/bundle.js:70138:10)
    at BlankLayout
    at FormProvider (http://localhost:8080/static/js/bundle.js:38313:31)
    at LocaleProvider (http://localhost:8080/static/js/bundle.js:5054:99)
    at ProviderChildren (http://localhost:8080/static/js/bundle.js:4468:24)
    at LocaleReceiver (http://localhost:8080/static/js/bundle.js:4942:99)
    at ConfigProvider (http://localhost:8080/static/js/bundle.js:4576:13)
    at I18nProvider (http://localhost:8080/static/js/bundle.js:2678:19)
    at Suspense
    at Locale (http://localhost:8080/static/js/bundle.js:9507:5)
    at App (http://localhost:8080/static/js/bundle.js:8812:62)
    at Router (http://localhost:8080/static/js/bundle.js:70161:15)
    at BrowserRouter (http://localhost:8080/static/js/bundle.js:69699:5)
    at RecoilRoot_INTERNAL (http://localhost:8080/static/js/bundle.js:78432:3)
    at RecoilRoot (http://localhost:8080/static/js/bundle.js:78588:5)

React will try to recreate this component tree from scratch using the error boundary you provided, ErrorBoundary.
logCapturedError @ react-dom.development.js:20085
index.js:56 TypeError: Cannot read properties of null (reading 'name')
    at index.jsx:64
    at useCreation (index.js:11)
    at TabRoute (index.jsx:61)
    at renderWithHooks (react-dom.development.js:14985)
    at updateFunctionComponent (react-dom.development.js:17356)
    at beginWork (react-dom.development.js:19063)
    at beginWork$1 (react-dom.development.js:23940)
    at performUnitOfWork (react-dom.development.js:22776)
    at workLoopSync (react-dom.development.js:22707)
    at renderRootSync (react-dom.development.js:22670) Object
BasicLayout.jsx:85 selectkey: null

**Comment by X-neuron** [comment]
刚打了webpack的 5.64.1 打包一半卡死。复现不了。
还不清楚你说的具体情况。 == webpack 修复自己的bug后再看看..
看你这情况是点的翻译 那个按钮么？

**Comment by flashtony2005** [comment]
谢谢回复，发现是matchRoutes 适配不了，我改了个名就行可以了 BasicLayout.jsx 中的第29 行 把 pathname 改成fullpath 就行了 
  const pickRoutes = memoized((routes, fullpath) => {
  let matches = matchRoutes(routes,  { fullpath });

**Comment by X-neuron** [comment]
感谢反馈，按道理不应该哇。我内网项目用这个做的，router 6 也是正式版最新的。 等搞明白打包卡半的情况再试试~

**Comment by flashtony2005** [comment]
调试了一下发现是matchRoutes  这个返回是null，也就是没有找到路径 ，例如  routes 的path 为 'c' ,   pathname 为'a/c' matchRoutes 返回 matches 为null ，是这个问题引起的。

**Comment by flashtony2005** [comment]
![1111](https://user-images.githubusercontent.com/186772/142332098-89c748e5-e35a-4cf1-b0c9-64009adf5a1d.gif)

**Comment by flashtony2005** [comment]
routers.js 里的 name: "系统功能",
   path: "/ab/*", 改成这样就行

**Comment by X-neuron** [comment]
刚复现了，应该这个地方的问题，当时做的时候react-router6是bata.0 做的。现在正式版，有些api 破坏性更新,有些地方改动还补小.. 明天修复下...感谢

**Comment by X-neuron** [comment]
@flashtony2005  初步查明是 prolayout 组件 使用的 route-utils  的问题 。transformRoutes.js 里会将输入的route.children 转换成route.routes 导致react-route6无法match到组件了。这个临时方案可以是深拷贝 个route 喂给prolayout的menu。要不就是发pr 等陈帅修复..

**Comment by X-neuron** [comment]
@flashtony2005  根本原因还是basiclayout.jsx 里  
```
const route = useCreation(
    () => translateNameProperty(orgRoute, locale),
    [orgRoute, locale],
  );
```
查看下useCreation 底层是 useRef  所以 逻辑本意是 不修改，实际上会被其他使用者 修改。导致的问题...
换成useMemo 应该能更快的解决问题

**Comment by X-neuron** [comment]
最新版已修复.... umijs的route tool不改，只能我临时改了...
